language: node_js

node_js:
  - '10'

cache: npm

git:
  depth: 3

install:
  - npx lerna bootstrap --no-ci

before_script:
  - npx lerna run build

jobs:
  include:
    - stage: lint
      name: Lint code
      script:
        - npx lerna run lint

    - stage: test
      name: Test code
      script:
        - npx lerna run test

    - stage: web-deploy
      name: Web deployment
      script:
        - npm run deploy:now
