language: node_js

node_js:
  - '10'

cache: npm

git:
  depth: 3

install:
  - npx lerna bootstrap --no-ci

jobs:
  include:
    - stage: lint
      name: Lint code
      script:
        - npx lerna run lint
        - commitlint-travis

    - stage: test
      name: Test code
      script:
        - npx lerna run test
