version: "3"

services:
  web:
    container_name: xarples-web
    build:
      context: .
      dockerfile: ./packages/web/development.Dockerfile
    environment:
      - HOST=0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - ./packages/web:/usr/src/console/packages/web/
      - /usr/src/console/packages/web/node_modules

  console:
    container_name: xarples-console
    build:
      context: .
      dockerfile: ./packages/console/development.Dockerfile
    ports:
      - 8001:8001
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      ACCOUNTS_HOST: accounts
    volumes:
      - ./packages/console:/usr/src/console/packages/console/
      - /usr/src/console/packages/console/node_modules

  accounts:
    container_name: xarples-accounts
    build:
      context: .
      dockerfile: ./packages/accounts/accounts/development.Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - redis
    environment:
      ACCOUNTS_HOST: 0.0.0.0
      ACCOUNTS_API_HOST: accounts-api
      REDIS_HOST: redis
    volumes:
      - accounts_node_modules:/usr/src/console/packages/accounts/accounts/node_modules
      - ./packages/accounts/accounts:/usr/src/console/packages/accounts/accounts/

  accounts-api:
    container_name: xarples-accounts-api
    build:
      context: .
      dockerfile: ./packages/accounts/accounts-api/development.Dockerfile
    ports:
      - 5001:5001
    depends_on:
      - postgres
    environment:
      ACCOUNTS_API_HOST: 0.0.0.0
      DB_HOST: postgres
    volumes:
      - accounts_api_node_modules:/usr/src/console/packages/accounts/accounts-api/node_modules
      - ./packages/accounts/accounts-api:/usr/src/console/packages/accounts/accounts-api/
      - ./packages/accounts/accounts-db:/usr/src/console/packages/accounts/accounts-db/
      - /usr/src/console/packages/accounts/accounts-db/node_modules

  postgres:
    container_name: postgres
    image: postgres:10.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: xarples
      POSTGRES_PASSWORD: xarples
      POSTGRES_MULTIPLE_DATABASES: xarples_accounts
    volumes:
      - ./docker/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379

volumes:
  accounts_node_modules:
  accounts_api_node_modules:
